# Generated by Django 5.2.4 on 2025-07-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('branch1', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('fee_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('is_verified', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highschool_math', models.IntegerField()),
                ('highschool_science', models.IntegerField()),
                ('highschool_english', models.IntegerField()),
                ('highschool_hindi', models.IntegerField()),
                ('plus2_physics', models.IntegerField()),
                ('plus2_chemistry', models.IntegerField()),
                ('plus2_math', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.studentprofile')),
            ],
        ),
    ]
