# Generated by Django 5.2.4 on 2025-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studentprofile_branch1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatallocation',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
