# Generated by Django 5.2.4 on 2025-07-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seatallocation_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch_allotted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='seat_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
