# Generated by Django 5.2.4 on 2025-08-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_result',
            field=models.FileField(blank=True, null=True, upload_to='results/10th/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelfth_result',
            field=models.FileField(blank=True, null=True, upload_to='results/12th/'),
        ),
    ]
