# Generated by Django 5.2.4 on 2025-08-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_studentprofile_aadhar_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='student',
        ),
    ]
