# Generated by Django 5.2.4 on 2025-07-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='branch',
            new_name='branch2',
        ),
    ]
