# Generated by Django 5.2.4 on 2025-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_marks_highschool_social_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch1',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch2',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE')], max_length=100, null=True),
        ),
    ]
