# Generated by Django 5.2.4 on 2025-08-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
