# Generated by Django 5.2.4 on 2025-08-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentprofile_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='Student', max_length=100),
            preserve_default=False,
        ),
    ]
