# Generated by Django 5.2.4 on 2025-08-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studentprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
