# Generated by Django 5.2.4 on 2025-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studentprofile_admin_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='aadhar_file',
            field=models.FileField(blank=True, null=True, upload_to='aadhaar_uploads/'),
        ),
    ]
