# Generated by Django 5.2.4 on 2025-09-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_userotp_otp_code_userotp_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(),
        ),
    ]
